### ISSUE TITLE
[bug] "account info" lead to ZeroDivisionError exception

### ISSUE THREAD

**Issue by vslash** [Gandi/gandi.cli#151]
# gandi account info
/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/gandi", line 9, in <module>
    load_entry_point('gandi.cli==0.16', 'console_scripts', 'gandi')()
  File "/usr/local/lib/python2.7/site-packages/gandi.cli-0.16-py2.7.egg/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/gandi.cli-0.16-py2.7.egg/gandi/cli/core/cli.py", line 168, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gandi.cli-0.16-py2.7.egg/gandi/cli/commands/account.py", line 15, in info
    account = gandi.account.all()
  File "/usr/local/lib/python2.7/site-packages/gandi.cli-0.16-py2.7.egg/gandi/cli/modules/account.py", line 38, in all
    left = account['credits'] / creditusage
ZeroDivisionError: integer division or modulo by zero
========================================================
env: 
# gandi api
API version: 3.3.32
# python -V 
Python 2.7.8
# pip list
-sqlite3 (0.0.0)
Babel (1.3)
ccsm (0.8.4)
CDApplet (1.0)
CDBashApplet (1.0)
chardet (2.2.1)
click (5.1)
Cython (0.21)
docutils (0.12)
gandi.cli (0.16)
gaupol (0.19.2)
html5lib (0.999)
IPy (0.83)
isodate (0.5.0)
Jinja2 (2.7.3)
libxml2-python (2.9.2)
lockfile (0.10.2)
MarkupSafe (0.23)
nose (1.3.3)
numpy (1.8.1)
pbr (0.10.0)
PIL (1.1.7)
pip (1.5.6)
pyenchant (1.6.5)
pygame (1.9.1release)
Pygments (1.6)
PyOpenGL (3.0.1)
PyPanel (2.4)
pyparsing (2.0.2)
Pyrex (0.9.9)
python-mpd (0.3.0)
python-xlib (0.12)
pytz (2014.4)
PyYAML (3.11)
rdflib (4.1.2)
requests (2.7.0)
setuptools (5.5.1)
six (1.8.0)
Sonata (1.6.2.1)
SPARQLWrapper (1.6.2)
Sphinx (1.2.3)
tagpy (2013.1)
Tkinter (0.0.0)
vboxapi (1.0)
wsgiref (0.1.2)
wxPython (3.0.0.0)
=========================================================

Regards,

--
v/

**Comment by sayoun** [comment]
Thanks I'll look into this asap.

**Comment by sayoun** [comment]
It's fixed in commit 2a596d441c75d45cd1843a6847d57f4e99b4e142
It will be included in next release 0.17 but you can use the latest master from github until then.

**Comment by vslash** [comment]
Ok, thanks, it works. for me.

**Comment by sayoun** [comment]
Fixed in release 0.17
