### ISSUE TITLE
Traceback when creating a certificate and passing an inexistant CSR file

### ISSUE THREAD

**Issue by klnikita** [Gandi/gandi.cli#157]
Everything is in the subject, a formatted error message would have been better.
```
$> gandi certificate create --csr badpath.csr --pk badpath.key --package cert_std_3_0_0 --dcv-method email
unable to load X509 request
4225887778448:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: CERTIFICATE REQUEST
Traceback (most recent call last):
  File "/home/nikita/devel/gandi.cli/venv/bin/gandi", line 9, in <module>
    load_entry_point('gandi.cli==0.16', 'console_scripts', 'gandi')()
  File "/home/nikita/devel/gandi.cli/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/nikita/devel/gandi.cli/gandi/cli/core/cli.py", line 168, in invoke
    click.Group.invoke(self, ctx)
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/nikita/devel/gandi.cli/venv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/nikita/devel/gandi.cli/gandi/cli/commands/certificate.py", line 325, in create
    common_name = gandi.certificate.get_common_name(csr)
  File "/home/nikita/devel/gandi.cli/gandi/cli/modules/cert.py", line 355, in get_common_name
    fhandle.name).split('=')[-1].strip()
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by sayoun** [comment]
Fixed in commit 8d1dba46475727a4af479fa5d2ef844bff1af2a5

**Comment by zaurky** [comment]
désolé, mais je pense pas que ce soit la bonne facon de le faire.
Check plutot si le fichier existe quand csr est pas a None.
