### ISSUE TITLE
paas info returns unsupported XML-RPC protocol

### ISSUE THREAD

**Issue by duub** [Gandi/gandi.cli#166]
yesterday I could use gandi.cli but today stoped working:
```
~> gandi paas list
Traceback (most recent call last):
  File "/usr/local/bin/gandi", line 9, in <module>
    load_entry_point('gandi.cli==0.16', 'console_scripts', 'gandi')()
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/cli.py", line 168, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/commands/paas.py", line 38, in list
    result = gandi.paas.list(options)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/modules/paas.py", line 34, in list
    return cls.call('paas.list', options)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/base.py", line 68, in call
    api = cls.get_api_connector()
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/base.py", line 58, in get_api_connector
    cls._api = XMLRPCClient(host=apihost, debug=cls.verbose)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/client.py", line 60, in __init__
    transport=GandiTransport(use_datetime=True, host=host))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1562, in __init__
    raise IOError, "unsupported XML-RPC protocol"
IOError: unsupported XML-RPC protocol
```

**Comment by engerim42** [comment]
try command:
```
    cat ~/.config/gandi/config.yaml | grep host
```
it should show this:
```
    host: https://rpc.gandi.net/xmlrpc/
```
You can also try this small sample Python script (replace APIkey with your 24 character key):
```
    import xmlrpclib
    api = xmlrpclib.ServerProxy('https://rpc.gandi.net/xmlrpc/')
    apikey = 'APIkey'
    version = api.version.info(apikey)
```
See: http://doc.rpc.gandi.net/overview.html

**Comment by duub** [comment]
so strange... I've made the test you've said and the first returned the url you wrote and the second the version 3.33.3 (I added a print(version)) and it's working again... may be a server error and I didn't had enough pattience?... thanks for your fast reply!
