### ISSUE TITLE
Updating DNS record result in OverflowError

### ISSUE THREAD

**Issue by mildis** [Gandi/gandi.cli#221]
When updating a DNS record, an OverflowError is thrown.

```
# gandi -vvv record update \
-r "$(gandi record list -f json example.com|jq -r ‘.[]|select(.name == "wopr")|[.name, .ttl, .type, .value]|@tsv'|tr '\t' ' ')" \
--new-record "wopr 300 A 8.8.8.8" example.com
[DEBUG] initialize connection to remote server
[DEBUG] calling method: domain.info
[DEBUG] with params: u’example.com'
Creating new zone file
[DEBUG] initialize connection to remote server
[DEBUG] calling method: domain.zone.version.new
[DEBUG] with params: 2831663
[DEBUG] initialize connection to remote server
[DEBUG] calling method: domain.zone.record.list
[DEBUG] with params: 2831663
[DEBUG] with params: 6
[DEBUG] with params: {‘type’: u’A’, 'name': u'wopr', 'value': u'192.168.1.1', 'ttl': 600}
Updating zone records
[DEBUG] calling method: domain.zone.record.update
[DEBUG] with params: 2831663
[DEBUG] with params: 6
[DEBUG] with params: {'id': 2268766733L}
[DEBUG] with params: {'type': u'A', 'name': u'wopr', 'value': u'8.8.8.8', 'ttl': 300}
Traceback (most recent call last):
  File "/usr/local/bin/gandi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/cli.py", line 221, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/commands/record.py", line 176, in update
    result = gandi.record.update(zone_id, record, new_record)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/modules/record.py", line 102, in update
    {'id': int(record[0]['id'])}, params_newrecord)
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/base.py", line 92, in call
    kwargs.get('return_dry_run', False)})
  File "/usr/local/lib/python2.7/dist-packages/gandi/cli/core/client.py", line 71, in request
    return func(apikey, *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 741, in dump_struct
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 686, in dump_long
    raise OverflowError, "long int exceeds XML-RPC limits"
OverflowError: long int exceeds XML-RPC limits
```

**Comment by sayoun** [comment]
Hello, this issue has already been fixed in latest master github branch, see issue https://github.com/Gandi/gandi.cli/issues/220

**Comment by mildis** [comment]
Yeah my bad, I did not see it.
