### ISSUE TITLE
gandi setup error

### ISSUE THREAD

**Issue by Maurozio** [Gandi/gandi.cli#223]
Hello,
I installed gandi.cli with pip and virtualenv. But I can't run the setup:
`maurizio@localhost:~> gandi setup
Welcome to GandiCLI, let's configure a few things before we start.

Traceback (most recent call last):
  File "/usr/bin/gandi", line 11, in <module>
    load_entry_point('gandi.cli==0.21', 'console_scripts', 'gandi')()
  File "/usr/lib/python3.6/site-packages/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/gandi/cli/core/cli.py", line 230, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/gandi/cli/commands/root.py", line 28, in setup
    gandi.init_config()
  File "/usr/lib/python3.6/site-packages/gandi/cli/core/conf.py", line 224, in init_config
    hidden_apikey = '%s...' % cls.get('api.key')[:6]
TypeError: 'NoneType' object is not subscriptable
`

Can you help me?
Thank you very much
Maurizio - Gandi customer

**Comment by sayoun** [comment]
Hello, this bug has been fixed in the master branch of github, I need to make a new release to update the pip version with the fix.

Thanks for reporting this, it will be done today.

**Comment by sayoun** [comment]
Hello, a new release is available, can you reinstall it from pip and test again ?

**Comment by Maurozio** [comment]
thank you very much for fixing the gandi setup!
I get an error running domain command options:
`maurizio@localhost:~> gandi domain create --domain example.com --duration 1                                                                                                        
/!\ --domain option is deprecated and will be removed upon next release.                                                                                                           
You should use 'gandi domain create example.com' instead.                                                                                                                          
Traceback (most recent call last):                                                                                                                                                 
  File "/usr/bin/gandi", line 11, in <module>                                                                                                                                      
    load_entry_point('gandi.cli==0.21', 'console_scripts', 'gandi')()                                                                                                              
  File "/usr/lib/python3.6/site-packages/gandi/cli/__main__.py", line 8, in main                                                                                                   
    cli(obj={})                                                                                                                                                                    
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__                                                                                                     
    return self.main(*args, **kwargs)                                                                                                                                              
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main                                                                                                         
    rv = self.invoke(ctx)                                                                                                                                                          
  File "/usr/lib/python3.6/site-packages/gandi/cli/core/cli.py", line 230, in invoke                                                                                               
    click.Group.invoke(self, ctx)                                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke                                                                                                      
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                        
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke                                                                                                       
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                 
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke                                                                                                       
    return callback(*args, **kwargs)                                                                                                                                               
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func                                                                                                
    return ctx.invoke(f, obj, *args[1:], **kwargs)                                                                                                                                 
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/gandi/cli/commands/domain.py", line 78, in create
    nameserver, background)
  File "/usr/lib/python3.6/site-packages/gandi/cli/modules/domain.py", line 43, in create
    raise DomainNotAvailable('%s is not available' % fqdn)
gandi.cli.core.utils.DomainNotAvailable: example.com is not available
maurizio@localhost:~> gandi domain create
Duration [1]: 1
Name of the domain: example.com
Traceback (most recent call last):
  File "/usr/bin/gandi", line 11, in <module>
    load_entry_point('gandi.cli==0.21', 'console_scripts', 'gandi')()
  File "/usr/lib/python3.6/site-packages/gandi/cli/__main__.py", line 8, in main
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/gandi/cli/core/cli.py", line 230, in invoke
    click.Group.invoke(self, ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/gandi/cli/commands/domain.py", line 78, in create
    nameserver, background)
  File "/usr/lib/python3.6/site-packages/gandi/cli/modules/domain.py", line 43, in create
    raise DomainNotAvailable('%s is not available' % fqdn)
gandi.cli.core.utils.DomainNotAvailable: example.com is not available
maurizio@localhost:~> 
`
Can you help me?
Thank you very much
