### ISSUE TITLE
Import Error: The 'packaging.requirements' package is required;

### ISSUE THREAD

**Issue by duub** [Gandi/gandi.cli#297]
Hello,
Using debian 10 & gandi.cli 1.5
I'm having this error:

```
Traceback (most recent call last):
  File "/home/duub/Development/gandi.cli/bin/gandi", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/duub/Development/gandi.cli/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/duub/Development/gandi.cli/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

```
Any idea where the problem is?

**Comment by duub** [comment]
solution:
`set PATH /home/duub/.local/bin $PATH
`
